(ns ai-zootson.util-test
  (:require [midje.sweet :refer :all]
            [ai-zootson.util :refer :all]))

(fact singularize
  (tabular
    (fact (singularize ?input) => ?output)
    ?input ?output

    "anteaters" "anteater"

    ;; Lets test all example animals...
    "aardvarks" "aardvark"
    "antelopes" "antelope"
    "basses" "bass"
    "bears" "bear"
    "boars" "boar"
    "buffaloes" "buffalo"
    "calves" "calf"
    "carps" "carp"
    "catfishes" "catfish"
    "cavies" "cavy"
    "cheetahs" "cheetah"
    "chickens" "chicken"
    "chubs" "chub"
    "clams" "clam"
    "crabs" "crab"
    "crayfishs" "crayfish"
    "crows" "crow"
    "deers" "deer"
    "dogfishes" "dogfish"
    "dolphins" "dolphin"
    "doves" "dove"
    "ducks" "duck"
    "elephants" "elephant"
    "flamingos" "flamingo"
    "fleas" "flea"
    "frogs" "frog"
    "fruitbats" "fruitbat"
    "giraffes" "giraffe"
    "girls" "girl"
    "gnats" "gnat"
    "goats" "goat"
    "gorillas" "gorilla"
    "gulls" "gull"
    "haddocks" "haddock"
    "hamsters" "hamster"
    "hares" "hare"
    "hawks" "hawk"
    "herrings" "herring"
    "honeybees" "honeybee"
    "houseflies" "housefly"
    "kiwis" "kiwi"
    "ladybirds" "ladybird"
    "larks" "lark"
    "leopards" "leopard"
    "lions" "lion"
    "lobsters" "lobster"
    "lynxes" "lynx"
    "minks" "mink"
    "moles" "mole"
    "mongooses" "mongoose"
    "moths" "moth"
    "newts" "newt"
    "octopuses" "octopus"
    "opossums" "opossum"
    "oryxes" "oryx"
    "ostriches" "ostrich"
    "parakeets" "parakeet"
    "penguins" "penguin"
    "pheasants" "pheasant"
    "pikes" "pike"
    "piranhas" "piranha"
    "pitvipers" "pitviper"
    "platypuses" "platypus"
    "polecats" "polecat"
    "ponies" "pony"
    "porpoises" "porpoise"
    "pumas" "puma"
    "pussycats" "pussycat"
    "raccoons" "raccoon"
    "reindeers" "reindeer"
    "rheas" "rhea"
    "scorpions" "scorpion"
    "seahorses" "seahorse"
    "seals" "seal"
    "sealions" "sealion"
    "seasnakes" "seasnake"
    "seawasps" "seawasp"
    "skimmers" "skimmer"
    "skuas" "skua"
    "slowworms" "slowworm"
    "slugs" "slug"
    "soles" "sole"
    "sparrows" "sparrow"
    "squirrels" "squirrel"
    "starfishes" "starfish"
    "stingrays" "stingray"
    "swans" "swan"
    "termites" "termite"
    "toads" "toad"
    "tortoises" "tortoise"
    "tuataras" "tuatara"
    "tunas" "tuna"
    "vampires" "vampire"
    "voles" "vole"
    "vultures" "vulture"
    "wallabies" "wallaby"
    "wasps" "wasp"
    "wolves" "wolf"
    "worms" "worm"
    "wrens" "wren"

    ;; Random
    "crises" "crisis"
    "businesses" "business"
    "axes" "axis"

    "viruses" "virus"
    "cactus" "cacti"
    ))

(fact singularize-singular
  (tabular
    (fact (singularize ?input) => ?input)
    ?input

    "anteater"

    ;; Lets test all example animals...
    "aardvark"
    "antelope"
    "bass"
    "bear"
    "boar"
    "buffalo"
    "calf"
    "carp"
    "catfish"
    "cavy"
    "cheetah"
    "chicken"
    "chub"
    "clam"
    "crab"
    "crayfish"
    "crow"
    "deer"
    "dogfish"
    "dolphin"
    "dove"
    "duck"
    "elephant"
    "flamingo"
    "flea"
    "frog"
    "fruitbat"
    "giraffe"
    "girl"
    "gnat"
    "goat"
    "gorilla"
    "gull"
    "haddock"
    "hamster"
    "hare"
    "hawk"
    "herring"
    "honeybee"
    "housefly"
    "kiwi"
    "ladybird"
    "lark"
    "leopard"
    "lion"
    "lobster"
    "lynx"
    "mink"
    "mole"
    "mongoose"
    "moth"
    "newt"
    "octopus"
    "opossum"
    "oryx"
    "ostrich"
    "parakeet"
    "penguin"
    "pheasant"
    "pike"
    "piranha"
    "pitviper"
    "platypus"
    "polecat"
    "pony"
    "porpoise"
    "puma"
    "pussycat"
    "raccoon"
    "reindeer"
    "rhea"
    "scorpion"
    "seahorse"
    "seal"
    "sealion"
    "seasnake"
    "seawasp"
    "skimmer"
    "skua"
    "slowworm"
    "slug"
    "sole"
    "sparrow"
    "squirrel"
    "starfish"
    "stingray"
    "swan"
    "termite"
    "toad"
    "tortoise"
    "tuatara"
    "tuna"
    "vampire"
    "vole"
    "vulture"
    "wallaby"
    "wasp"
    "wolf"
    "worm"
    "wren"

    ;; Random
    "crisis"
    "business"
    ))
